# Python
language: python

python:
  - 3.7

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

# Branch Whitelist
branches:
  only:
    - master

# Dependencies
install:
  - pip install -r requirements.txt
  - pip install flake8 pytest coverage coveralls
  - pip install Sphinx sphinx_rtd_theme

# Tests
script:
  - flake8 bobocep
  - coverage run --source=bobocep/ setup.py test

after_success:
  - coveralls

before_deploy:
  if ! [[ $TAG_DEPLOY_GITHUB_PAGES ]]; then
    cd docs &&
    sphinx-apidoc -o source/modules ../bobocep &&
    make html &&
    cd ..;
  fi

deploy:
  - provider: pypi
    user: __token__
    password: $TOKEN_PYPI_BOBOCEP
    on:
      tags: true

  - provider: pages
    tag_name: $TAG_DEPLOY_GITHUB_PAGES
    github-token: $TOKEN_GITHUB_PAGES
    skip_cleanup: true
    keep_history: true
    local-dir: docs/build/html
    target_branch: gh-pages
    verbose: true
    #on:
    #  tags: true
