# Python
language: python

python:
  - 3.7

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

# Branch Whitelist
branches:
  only:
    - master

# Dependencies
install:
  - pip install -r requirements.txt
  - pip install flake8 pytest coverage coveralls

# Tests
script:
  - flake8 bobocep
  - coverage run --source=bobocep/ setup.py test

after_success:
  - coveralls
