# Python
language: python

python:
  - 3.7

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true


# Branch Whitelist
branches:
  only:
    - master


# Dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_tests.txt
  - pip install -r requirements_docs.txt


# Tests
script:
  - flake8 bobocep
  - coverage run --source=bobocep/ setup.py test


# Code Coverage, Docs Build
after_success:
  - coveralls
  - cp -a $TRAVIS_BUILD_DIR/. /tmp/bobocep
  - cd /tmp/bobocep/docs
  - sphinx-apidoc -o source/modules ../bobocep && make html
  - cd $TRAVIS_BUILD_DIR


# PyPI, GitHub Pages
deploy:
  - provider: pypi
    user: __token__
    password: $TOKEN_PYPI_BOBOCEP
    on:
      tags: true

  - provider: pages
    github-token: $TOKEN_GITHUB_PAGES
    skip_cleanup: true
    keep_history: false
    local-dir: /tmp/bobocep/docs/build/html
    target_branch: gh-pages
    verbose: true
    on:
      tags: true
