name: CICD

on:
  push:

jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ "3.9", "3.10" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 ./bobocep --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 ./tests --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Type check with mypy
        run: |
          mypy ./bobocep
          mypy ./tests

      - name: Code coverage with coverage and pytest
        run: |
          coverage run --source=bobocep -m pytest tests
          coverage report --fail-under=98

      - name: Documentation coverage with interrogate
        run: |
          interrogate -vv bobocep --fail-under 98

      - name: Upload code coverage to Code Climate
        uses: paambaati/codeclimate-action@v2.5.3
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_TEST_REPORTER_ID }}
        with:
          coverageCommand: coverage xml
  cd:
    name: CD
    needs: ci
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.9" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user

      - name: Build binary wheel and source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/

      - name: Publish to Test PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TEST_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
