name: CI/CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ 3.7, 3.8, 3.9, 3.10 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names.
          flake8 ./bobocep --count --select=E9,F63,F7,F82 --show-source --statistics

          # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide.
          flake8 ./bobocep --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          coverage run --source=bobocep -m pytest tests

      - name: Generate coverage report
        run: |
          coverage combine
          coverage report --fail-under=100          

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: html-report
          path: htmlcov
