name: Security

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  schedule:
    - cron: '0 6 * * 1'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ "python" ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: CodeQL initialize
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: CodeQL autobuild
      uses: github/codeql-action/autobuild@v1

    - name: CodeQL analysis
      uses: github/codeql-action/analyze@v1
